### ISSUE TITLE
Photo Ratings incorrectly entered as "0" from reports search result

### ISSUE THREAD

**Issue by gintner** [jeroenrnl/zoph#112]
When a user goes to the "reports" tab, then clicks on the link for unrated photos, as expected a list of unrated photos is presented.  The user clicks on the first thumbnail in the results.  When the user then selects a rating from the pull down box and clicks the "rate" button, the rating is entered as "0" in the database instead of the selected value.  This behavior is observed using both the Firefox and Chrome browsers on both Linux and Windows operating systems.

If the same user goes to the "Albums" tab and browses to a photo album containing unrated photos, they can select a rating from the pull down box and click rate.  The result is what is expected: the photo receives the proper rating in the database.

We are using version 0.9.11. Our installation contains nearly 15,000 photos in 300 albums.

**Comment by jeroenrnl** [comment]
Hi,
Good to see that people are using Zoph with large amounts of photos!
Would you mind logging your issue on https://gitlab.com/jeroenrnl/zoph/-/issues as I have switched Zoph to there.

**Comment by jeroenrnl** [comment]
https://gitlab.com/jeroenrnl/zoph/-/issues/125

Thanks!
