### ISSUE TITLE
Installing Zoph on a Raspberry Pi 4 Model B

### ISSUE THREAD

**Issue by RayL-ui** [jeroenrnl/zoph#113]
I have attempted to install zoph-v0.9.19 on a RasPi 4 Model B after updating the Pi PHP to PHP 8.0, MariaDB 10.3 and ImageMagick to version 7.1.0 on the Raspbian OS but was unsuccessful in getting v0.9.19 to upload photos. The user interface allowed adding users however I was unable to upload photos. I am very familiar with the import process on my current working  Zoph 0.9.6 but found the v0.9.19 process to apparently be much different or else something is not working. I would be very happy to supply screenshots and more information if you can tell me what would be useful to you. I looked over the FreedomBox website but was not able to find anything applicable.

Ultimately I want to move my Zoph 0.9.6 data up to a much more current Zoph version. One question > can I execute the zoph-update SQL files using PHP 8.0 or does each need to be done with the PHP version appropriate to the specific update file?

Thank you very much for any help you may be able to provide. I am committed to test and provide feedback to any suggestion or request that you may have.
Ray

**Comment by jeroenrnl** [comment]
Hi Ray,

I'm no longer using Github for Zoph, would you mind recreating the issue at https://gitlab.com/jeroenrnl/zoph/-/issues?

And, yes, please include some screenshots of the issues you're running in.

Thanks,
Jeroen

**Comment by jeroenrnl** [comment]
See https://gitlab.com/jeroenrnl/zoph/-/issues/196
