### ISSUE TITLE
Further options in Web Import

### ISSUE THREAD

**Issue by lizdodd** [jeroenrnl/zoph#32]
It would be appreciated if further fields could be filled from the Web Import page
eg the remaining fields from http://en.wikibooks.org/wiki/Zoph/Importing_photos/Using_the_CLI/zoph_CLI_client#--fields and the option 'mapzoom'

**Comment by jeroenrnl** [comment]
@lizdodd I am working on this now and I am wondering about the mapzoom support, is this something that could maybe be implemented as a global configuration? Would you really want to set it per (group of) photo(s) during import or is it something that you would always set to the same number?

**Comment by lizdodd** [comment]
On Wed, 11 Nov 2015 12:15:24 -0800
Jeroen Roos <notifications@github.com> wrote:

> @lizdodd I am working on this now and I am wondering about the
> mapzoom support, is this something that could maybe be implemented as
> a global configuration? Would you really want to set it per (group
> of) photo(s) during import or is it something that you would always
> set to the same number?
> 

Jeroen 
I usually set it to the same number, just that it being forced to zero
is a bad choice.
I would be happy with a global user preference for this for the web
import.

**Comment by jeroenrnl** [comment]
@lizdodd I ended up making it possible to just choose it during import
