### ISSUE TITLE
Subgroupings of 'persons'

### ISSUE THREAD

**Issue by lizdodd** [jeroenrnl/zoph#44]
I'd like to suggest subgroupings of persons 
which I might make 
Family
Friends
Work Colleagues
because as the number of persons expands, the list becomes difficult to manage.

**Comment by jeroenrnl** [comment]
Done

**Comment by jeroenrnl** [comment]
I found out that I have missed something quite essential... I forgot to add a way to add people to a circle... I suppose I should fix that :smile:

**Comment by jeroenrnl** [comment]
Done.
Really, this time.
