### ISSUE TITLE
Zoph 0.9.1: php_loc in class autoloader does not work

### ISSUE THREAD

**Issue by christoph-moder** [jeroenrnl/zoph#62]
Zoph failed with an PHP error:
> PHP Fatal error:  Class 'settings' not found in /var/www/zophdir/include.inc.php on line 30

The reason seems that `settings::$php_loc` is not set; the following workaround in include.inc.php helped:
```php
#if(is_readable(settings::$php_loc . "/" . $file)) {
if(is_readable( dirname($_SERVER['SCRIPT_FILENAME']) . "/" . $file)) {

**Comment by jeroenrnl** [comment]
I will look into this

**Comment by jeroenrnl** [comment]
I am sorry, I totally forgot about this one. I've tried to reproduce it, but I do not get the error. Could you explain in what situation you see this?

**Comment by jeroenrnl** [comment]
@christoph-moder I cannot reproduce this issue, is it still a problem for you?

**Comment by christoph-moder** [comment]
Hi Jeroen,

Am 2015-06-17 22:31, schrieb Jeroen Roos:
> @christoph-moder [1] I cannot reproduce this issue, is it still a
> problem for you?

Sorry, I don't have time to investigate it further - maybe there was 
something special about my installation, and my workaround has solved 
it. Since you cannot reproduce it, just leave it at that.

Thanks for your effort!

Christoph

**Comment by jeroenrnl** [comment]
OK, feel free to reopen if you re-encounter this...
