### ISSUE TITLE
Error: CliException class not found

### ISSUE THREAD

**Issue by christoph-moder** [jeroenrnl/zoph#63]
> PHP Fatal error:  Class 'CliException' not found in /var/www/zophdir/exception.inc.php on line 43

Workaround: move the declaration of CliException *before* its first use in exception.inc.php.

**Comment by jeroenrnl** [comment]
That's not a workaround! That's a solution! :smile:
I just don't understand how it can be that I have never seen this error... I will look into it.

**Comment by jeroenrnl** [comment]
Ok, it turned out to be a workaround in the end, OrganizerException is not supposed to be extended from CliException but from ZophException. (still puzzles me that I never saw that error!)
