### ISSUE TITLE
Problem with Install

### ISSUE THREAD

**Issue by micksulley** [jeroenrnl/zoph#64]
Just trying to install Zoph by following the wiki.  When I try to access is with a browser I get - 
Fatal Error: db_host, db_name, db_user, db_pass or db_prefix setting missing from /etc/zoph.ini
fatal error

In /etc/zoph.ini I have -
[zoph]
db host = "localhost"
db_name = "zoph"
db_user = "zoph_rw"
db_pass = "pass"
db_prefix = "zoph_"

php_location = /var/www/zoph

What am I missing here?

**Comment by jeroenrnl** [comment]
Check the second line, it's missing an underscore...

**Comment by jeroenrnl** [comment]
@micksulley Did this solve your problem?

**Comment by micksulley** [comment]
Sorry for the delay, yes it did, it is running now, thank you.
