### ISSUE TITLE
PHP Undefined index errors from group.php

### ISSUE THREAD

**Issue by JohnLines** [jeroenrnl/zoph#65]
If, under Admin/Groups, I attempt to edit the albums available to a group, for example to add a new album I see in the Apache log

 PHP Notice:  Undefined index: _remove_user in /usr/share/zoph/group.inc.php on line 40, referer: http://iris.localdomain/zoph/group.php?_action=edit&group_id=3

or if adding a new group and giving it access to all existing albums I see messages like

 PHP Notice:  Undefined index: _remove_permission_album__182 in /usr/share/zoph/group.php on line 51, referer: http://iris.localdomain/zoph/group.php

and in the case of adding albums to an existing group the albums do not appear to be added, whereas creating a new group and adding all the albums does seem to work.

I am running zoph 0.9.1, upgraded from 0.8.0.1

**Comment by jeroenrnl** [comment]
I think I ran into this while developing and fixed this for 0.9.2, but since that is far from complete, I will see if I can fix it in a bugfix release... I'll look into it.

**Comment by jeroenrnl** [comment]
Confirmed, I can reproduce this on my system.

**Comment by jeroenrnl** [comment]
I have cancelled v0.9.1.1, but this bug is fixed in v0.9.2 as well
