### ISSUE TITLE
Unable to upload via Web GUI

### ISSUE THREAD

**Issue by duncan25** [jeroenrnl/zoph#81]
Hi Guys,

Not sure where i am going wrong here so i hope someone can help me.

I have just finished installing the Zoph package and am able to login to the Web GUI.  The database and user accounts are all created successfully.

The issue i am having is that i am unable to upload any images through the GUI.  I keep getting the error **_"FATAL ERROR: /data/upload/images does not exist, and i can not create it. (Could not create directory: /data/) webimport.inc.php: 137.
fatal error"_**

I have checked the /var/log/apache/error.log and it says the same thing, it cannot find the /data/images/upload directory. The file is also being uploaded from the /home/user/Pictures directory.

I have created the directory within /var/www/html/zoph/ as /data/images/upload.  Have i created the directory in the correct location?  

Any help is appreciated

Thanks,

**Comment by duncan25** [comment]
Here is a copy of some output from the error log:

[Mon Aug 29 14:43:49.285072 2016] [:error] [pid 5309] [client 127.0.0.1:48386] PHP Warning:  scandir(): (errno 2): No such file or directory in /var/www/html/zoph/file.inc.php on line 335, referer: http://localhost/zoph/import.php
[Mon Aug 29 14:43:49.285092 2016] [:error] [pid 5309] [client 127.0.0.1:48386] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/zoph/file.inc.php on line 338, referer: http://localhost/zoph/import.php

**Comment by duncan25** [comment]
Ok so after some further testing, i have found that  by creating the /data/images/upload directory structure in the "/", i can upload images.

where can i change this path as i would like to have it elsewhere?

thanks,

**Comment by jeroenrnl** [comment]
Correct. The images directory is referenced from the root. 
You can change it if you log in as an "admin" user and go to "admin" -> "config". Then under "paths", it's the first setting.
I am changing this into a bug, because this should be in the documentation and it's currently not clearly described.

**Comment by duncan25** [comment]
Thanks for your answer.  This was very helpful.

I will make the changes now. :)

**Comment by jeroenrnl** [comment]
Reopening because I still need to work on the documentation

**Comment by jeroenrnl** [comment]
I have updated the documentation. It now properly describes how to configure this. I also removed a lot of references to the "old way" of configuration.
