### ISSUE TITLE
Zoph 0.9.3 command line import crashing

### ISSUE THREAD

**Issue by lizdodd** [jeroenrnl/zoph#84]
I was trying to use the webimport and somehow that wouldn't work. so I thought that the CLI would serve the same purpose. 
I get this consistent error
PHP Fatal error:  Class 'db\db' not found in /var/www/zoph/settings.inc.php on line 121

**Comment by jeroenrnl** [comment]
I have just tested this on my system and there it works without an issue.
Does Zoph work otherwise? Can you see photos that are already in your database? Is this an issue that surfaced after upgrading to 0.9.3 or have you been running on 0.9.3 for a longer time?

**Comment by lizdodd** [comment]
1. Zoph works otherwise.
2. Photos are visible
3. This is the first time I have used the CLI import on 0.9.3

**Comment by jeroenrnl** [comment]
I can reproduce your issue if I try to use the `zoph` CLI client from v0.9.1 with a v0.9.3/v0.9.4 installation of Zoph. Could it be that you forgot to update the CLI client?
You can easily check if your client is the correct one:
````
$ cat `which zoph` | grep CLI_API
define("CLI_API", 4);
````
If the API is defined as 3 or lower, it's not the most current version.

**Comment by lizdodd** [comment]
On Tue, 13 Sep 2016 00:18:15 -0700
Jeroen Roos <notifications@github.com> wrote:

> I can reproduce your issue if I try to use the `zoph` CLI client from
> v0.9.1 with a v0.9.3/v0.9.4 installation of Zoph. Could it be that
> you forgot to update the CLI client? You can easily check if your
> client is the correct one: ```` $ cat `which zoph` | grep CLI_API
> define("CLI_API", 4);
> ````
> If the API is defined as 3 or lower, it's not the most current
> version.
> 

Thanks for that!

I get "3" as the result.

**Comment by jeroenrnl** [comment]
In that case you should replace the "zoph" executable with the one from v0.9.3 (or 0.9.4 - which should come out this week)
