### ISSUE TITLE
WebImport has no error dialogue

### ISSUE THREAD

**Issue by lizdodd** [jeroenrnl/zoph#85]
When trying to import a photo which is already in the database, the webimport gives no feedback, and nothing happens.
If this photo is the first of a group, nothing gets imported.
I suggest we need some error dialogues.

**Comment by jeroenrnl** [comment]
Ok, now the other problem is fixed, let's look into this one :smile:

**Comment by jeroenrnl** [comment]
I have tried the following:
- Use the webimport to upload a file
- Imported it, using the webimport
- Then uploaded the same file, another time
- And, trying to import it again.
- In the "Details" section of the Import page, the following error is displayed:
````
Fatal error: Uncaught exception 'FileExistsException' with message 
'File already exists: /data/images/Photo_1.JPG' in /var/www/zoph/php/classes/file.inc.php:224 
Stack trace: 
#0 /var/www/zoph/php/classes/file.inc.php(236): file->checkCopy() 
#1 /var/www/zoph/php/classes/photo.inc.php(466): file->checkMove()
#2 /var/www/zoph/zoph/php/import.inc.php(129): photo->import(Object(file))
#3 /var/www/zoph/php/webimport.inc.php(59): Import::photos(Array, Array)
#4 /var/www/zoph/php/import.php(147): WebImport::photos(Array, Array)
#5 {main} thrown in /var/www/zoph/php/classes/file.inc.php on line 224
````
Although it is not the most user-friendly error, an error is displayed. Is this the situation you mean?

**Comment by jeroenrnl** [comment]
I tried a different scenario:
- Use the webimport to upload a file
- Use the webimport to upload the same file, another time.
Now, the "Upload photo" section displays:
````
Fatal Error: A file named Photo_2.JPG already exists in /data/images/upload webimport.inc.php: 153.
fatal error
`````

**Comment by lizdodd** [comment]
On Tue, 13 Sep 2016 02:01:06 -0700
Jeroen Roos <notifications@github.com> wrote:

> I tried a different scenario:
> - Use the webimport to upload a file
> - Use the webimport to upload the same file, another time.
> Now, the "Upload photo" section displays:
> ````
> Fatal Error: A file named Photo_2.JPG already exists
> in /data/images/upload webimport.inc.php: 153. fatal error
> `````
> 

I've had that happen with the CLI, but been caught more than once with
no error dialogue on the webimport.

I've got a few hundred to go from last month, I'm sure I can make this
happen again, and report back.

Even the first error you got would have had me look in the right place!

**Comment by jeroenrnl** [comment]
For now, I'll assume this is fixed. If you still have issues, please feel free to reopen
