### ISSUE TITLE
Upgrade to 0.9.5

### ISSUE THREAD

**Issue by lizdodd** [jeroenrnl/zoph#86]
I've just upgraded following the UPGRADE.md instructions. I hadn't gone to 0.9.4 it seems, and after upgrading my install still says 0.9.3
There are no instructions to update the cli scripts. I've been caught before with outdated cli, so was looking carefully for upgrade instructions. 
I'm sure there has been a change, the program is much faster at finding random photos from a massive database.

**Comment by jeroenrnl** [comment]
Hi Liz,
Have you copied ``config.inc.php`` as well, or did you replace it with your own ("old") version? This file contains the version number...

I've just checked, in fact the CLI tool will need to be copied as well. I've added this to the upgrade instructions.

Please let me know if this fixes it for you...

Thanks!
Jeroen

**Comment by jeroenrnl** [comment]
Hi @lizdodd - could you let me know if the above helps you?

**Comment by lizdodd** [comment]
On Sun, 05 Feb 2017 12:13:14 -0800
Jeroen Roos <notifications@github.com> wrote:

> Hi Liz,
> Have you copied ``config.inc.php`` as well, or did you replace it
> with your own ("old") version? This file contains the version
> number...
> 
> I've just checked, in fact the CLI tool will need to be copied as
> well. I've added this to the upgrade instructions.
> 
> Please let me know if this fixes it for you...
> 
> Thanks!
> Jeroen
> 

I copied the CLI tool across, but haven't copied "config.inc.php"

Liz

**Comment by jeroenrnl** [comment]
Since the file ```config.inc.php``` contains the version number, this explains why you see the old version number. There are very little settings still set from ```config.inc.php```, so in most cases it should be safe to overwrite it.

**Comment by jeroenrnl** [comment]
@lizdodd Is this solved now?

**Comment by lizdodd** [comment]
On Wed, 22 Feb 2017 12:26:42 -0800
Jeroen Roos <notifications@github.com> wrote:

> @lizdodd Is this solved now?
> 

This is all sorted out now.

**Comment by jeroenrnl** [comment]
Thanks
