### ISSUE TITLE
Cannot add a new place

### ISSUE THREAD

**Issue by lizdodd** [jeroenrnl/zoph#90]
Zoph 0.9.5
Go to Places, select "new", and the main part of the display is blank (everything under the breadcrumb trail).

**Comment by lizdodd** [comment]
![Uploading Screenshot_2017-02-28_15-51-59.v01.jpg…]()

**Comment by lizdodd** [comment]
Same result trying to edit a place. I tried to add a screenshot but it was unsuccessful

**Comment by jeroenrnl** [comment]
Could you turn on some debugging and post output?
for example by adding
```error_reporting(E_ALL);```
to ```config.inc.php```

**Comment by jeroenrnl** [comment]
@lizdodd If you are running Zoph on a system with MySQL 5.7 (Not MariaDB), you may be having the problem described in issue #88 - link to a fix in the last comment.

**Comment by jeroenrnl** [comment]
@lizdodd Could you update me if this is still an issue for you?
Please try with the last snapshot from the issue#88 branch:
https://github.com/jeroenrnl/zoph/archive/issue%2388.zip

**Comment by lizdodd** [comment]
Sorry for the delay.
I established that I was using MySQL 5.5
Then downloaded Zoph 0.9.6
and still cannot add a new place.

So I upgraded the server to Debian GNU/Linux 8 \n \l
The MySQL is now  5.5.55-0+deb8u1
and I have not solved the problem.

I put in the debug requested into config.inc.php
and this is the output. (ip address obfuscated)


[Sat May 27 20:54:40.272169 2017] [:error] [pid 7741] [client
111.111.111.111:40726] PHP Catchable fatal error:  Argument 1 passed to
template\\template::addBlock() must be an instance of template\\block,
null given, called in /var/www/zoph/edit_place.inc.php on line 44 and
defined in /var/www/zoph/classes/template/template.inc.php on line 171,
referer: http://billiau.net/zoph/places.php

**Comment by jeroenrnl** [comment]
Reproduced

**Comment by jeroenrnl** [comment]
This actually was a double bug that had to do with the warning a browser can display when Javascript is off.
1. Whenever a page was loaded that contains items that require Javascript, Zoph would check if it needed to display the warning. If it was NOT needed, it would throw an error
2. It would think it was needed in too many cases, this caused me to not be able to reproduce the issue until you pointed me at exactly the right line.
