### ISSUE TITLE
Database connection not using utf8 charset

### ISSUE THREAD

**Issue by Pontusfroding** [jeroenrnl/zoph#92]
I live in Sweden and we have some strange names with å ä ö in them ;)

There is some problem with the encoding which I discovered when I tried to edit and add some people. I cant add and edit people because it just gives me a blank page, so I was gonna do it direct in the database. Then I saw that the encoding in the database was wrong. ö looks like  Ã¶ in the database and if I change them there to ö then it will be wrong on the web.

After changing line 61 in /php/classes/db/db.inc.php it works but I will have to change all the names since they were saved wrong before. Maybe it is possible to make the changes automatic in some way but that's above my knowledge for the moment. 

The changes on line 61 
-        static::$connection=new PDO($dsn,$dbuser,$dbpass);
+        static::$connection=new PDO($dsn,$dbuser,$dbpass,array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'));

**Comment by jeroenrnl** [comment]
You could try following this procedure to convert your database to UTF-8: https://en.wikibooks.org/wiki/Zoph/Upgrading/Changing_your_database_to_UTF-8

**Comment by Pontusfroding** [comment]
My database is in utf8 so that will probably not help (I think)? But it's no problem for me, I only have like 4 people with ö in the name.
